---
title: "Part 5 solutions"
author: "D-Lab"
date: "3/31/2019"
output: html_document
---

## Part 5 - Challenge 1

1. Write a for loop that outputs something. 

```{r}
# 1. 
for (i in 1:10) {
  print(i / 12)
}

# Or

for (time in c(12, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)) {
  print(paste("The time is", paste0(time, "AM")))
}
```

## Part 5 - Challenge 2

1. Write a for loop that uses `if` and `else`

```{r}
for (x in c(2,4,6,8,10,12)) {
  if (x < 8) {
    print(paste(x, "is less than 8"))
  }else{
    print(paste(x, "is greater than or equal to 8"))
  }
}

# Or

for (i in 1:12) # what happened to the curly braces? 
    if (i < 10) {
        print(paste("The time is", i, "o'clock"))
        }else{
        print("It is getting late!")
}
```

## Part 5 - Challenge 3

What is happening in the code for a simple combination lock below? 

```{r}
# combination lock example

# 1. Generate some lock combinations 
set.seed(123)
combos = paste0(sample(1:60,100, replace = T), "-",  # paste0 or paste?
              sample(1:60,100, replace = T), "-", 
              sample(1:60,100, replace = T))
combos

# 3. Write a function to test each of the combinations
lock = function(x) {
for(x in 1:length(combos)){
  if(combos[x] == "24-40-38"){
    print(paste(combos[x], ":", "unlock"))
}else{
  print(paste("ERROR", ":", combos[x]))
}
}
}

# 3. Test combinations and view results
lock(combos)
```