---
title: "R Fundamentals Part4-1: putting it all together"
author: "D-Lab"
date: "March 31, 2019 (updated `r Sys.Date()`)"
output: 
  html_document: 
    toc: yes
    toc_float: yes
---

# Putting it all together

So what does it all mean? As fun as data science is, we do not do it for nothin'. We do it as a tool to finish our theses/dissertations and earn our degrees, understand weather and climate change, find breakthroughs in cancer screening or drug testing, or improve the profit margins of our business. Revisit the example workflow from Part3-1_review and objectives. 

## An example workflow 

1. Read the literature in your field. What suggested directions should you proceed in? Where are the gaps in the scientific knowledge? What is missing, is lacking, or otherwise needs to be expanded upon?  
2. Ask a well-informed research question using your literature review.  
3. Turn your research question into a set of testable hypotheses.  
4. Design data collection protocols/obtain data somehow.  
5. Import this data into R and clean/subset it.  
6. Compute descriptive statistics.  
7. Generate visualizations.  
8. Your data summaries and visualizations should (hopefully) indicate what you should specifically test. Descriptive statistics and plots help check for any obvious (or not so obvious) signals or relationships. Statistical testing can then be employed to test such relationships.  

## Heart disease dataset

You are given a dataset you have never seen before. Can you replicate the above workflow? 

##### Load the `heart.csv` dataset.  
```{r}
## YOUR CODE HERE
```

